import Head from "next/head";
// import styles from "@/styles/Home.module.css";
import Link from "next/link";

//import pour key unique
import { v4 as uuidv4 } from "uuid";

export default function Home(props) {
  //props renvoie un tableau d'objets
  console.log(props, "log de props-------");
  return (
    <>
      <Head>
        <title>NewsAPI app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* d-flex pour display:flex et fle-column pour flex-direction:column */}
      <div className="container px-3 pt-5 d-flex flex-column ">
        <h2 className="text-center fw-bolder my-2">Les dernières actualités</h2>

        <div className="row justify-content-center mt-5">
          {props.data.articles.map((item) => (
            // la div tient tout l'ecrzn en small (12) et 7/12 en lazrge screen
            <div className="col-12 col-lg-7 m-3" key={uuidv4()}>
              <div className="card shadow">
                <div className="card-body">
                  <h5 className="card-title my-2">{item.title}</h5>
                  <h6 className="card-subtitle my-3 text-black-50 ">
                    {item.author} - {item.publishedAt.slice(0, 10)}
                  </h6>
                  <Link
                    legacyBehavior
                    className="ml-auto card-link"
                    href={item.url}
                  >
                    {/* text-decoration none pour enlever le souligné du lien */}
                    <a className="ml-auto text-decoration-none">voir plus</a>
                  </Link>
                  {/* <a className="btn btn-outline-danger">test</a> */}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Il va falloir faire une requete au back et retourner les news */}
      </div>
    </>
  );
}

export async function getStaticProps() {
  const result = await fetch("http://localhost:3000/getnews");

  const data = await result.json();

  //data renvoie bien un objet avec un tableau d'articles
  console.log(data);

  return { props: { data } };
}
