import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

//import pour key unique
import { v4 as uuidv4 } from "uuid";

export default function Home(props) {
  //props renvoie un tableau d'objets
  console.log(props, "log de props-------");
  return (
    <>
      <Head>
        <title>NewsAPI app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container px-4 pt-5">
        <h2 className="text-center my-2">Les dernières actualités en France</h2>
        <div className="row justify-content-center mt-5">
          {props.data.articles.map((item) => (
            <div className="col-12 col-lg-6 m-3" key={uuidv4()}>
              <div className="card h-150 shadow-sm">
                <div className="card-body">
                  <h5 className="card-title my-2">{item.title}</h5>
                  <h6 className="card-subtitle my-3 text-muted ">
                    {item.author} - {item.publishedAt.slice(0, 10)}
                  </h6>
                  <Link
                    legacyBehavior
                    className="ml-auto card-link"
                    href={item.url}
                  >
                    voir plus
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Il va falloir faire une requete au back et retourner les news */}
      </div>
    </>
  );
}

export async function getStaticProps() {
  const result = await fetch("http://localhost:3000/getnews");

  const data = await result.json();

  //data renvoie bien un objet avec un tableau d'articles
  console.log(data);

  return { props: { data } };
}
